# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 01:08
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=10)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/open_work/photos'), upload_to=b'')),
            ],
        ),
    ]
