# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_work', '0003_auto_20170118_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
