# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 20:42
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('open_work', '0007_auto_20170118_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='body',
            field=redactor.fields.RedactorField(default=''),
        ),
    ]
