# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_work', '0009_jobs_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='tag',
            field=models.CharField(default='\u5de5\u50b7', max_length=20),
        ),
    ]
