# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_work', '0010_auto_20170119_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
